import datetime

# this time dotenv-import was already in upstream-file
from dotenv import load_dotenv

load_dotenv()

from langchain_core.output_parsers.openai_tools import (
    JsonOutputToolsParser,
    PydanticToolsParser,
)
from langchain_core.messages import HumanMessage
# On MessagePlaceholder
# (class) MessagesPlaceholder
# Prompt template that assumes variable is already list of messages.
# A placeholder which can be used to pass in a list of messages.
# Direct usage:
#    .. code-block:: python
#   from langchain_core.prompts import MessagesPlaceholder
#       prompt = MessagesPlaceholder("history")
#       prompt.format_messages() # raises KeyError
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_openai import ChatOpenAI

from schemas import AnswerQuestion, ReviseAnswer

# kept o4-mini at first
llm = ChatOpenAI(model="o4-mini")
parser = JsonOutputToolsParser(return_id=True)
# pydantic parser transforms output of LLM into the class-structure of AnswerQuestion
parser_pydantic = PydanticToolsParser(tools=[AnswerQuestion])

# 1. {first_instruction} -> initial generated input based on the user query
# 2. Reflect and critique your answer. Be severe to maximize improvement. -> will be input for revisor later
# 3. Recommend search queries to research information and improve your answer. -> search queries for the tools
# .partial allows to preset some of the variables; here we set the time-variable

actor_prompt_template = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            """You are expert researcher.
Current time: {time}

1. {first_instruction}
2. Reflect and critique your answer. Be severe to maximize improvement.
3. Recommend search queries to research information and improve your answer.""",
        ),
        MessagesPlaceholder(variable_name="messages"),
        ("system", "Answer the user's question above using the required format."),
    ]
).partial(
    time=lambda: datetime.datetime.now().isoformat(),
)

# extension/specification of actor_prompt_template
# > here the missing variable "first_instruction" is set 
first_responder_prompt_template = actor_prompt_template.partial(
    first_instruction="Provide a detailed ~250 word answer."
)

# take extended prompt template and chain it into the llm
# further bind the AnswerQuestion-class to the llm and enforce it via tool_choice
# > this shall ensure that output generated by the first_responser chain fits the correct structure
# > "Grounding"
first_responder = first_responder_prompt_template | llm.bind_tools(
    tools=[AnswerQuestion], tool_choice="AnswerQuestion"
)

revise_instructions = """Revise your previous answer using the new information.
    - You should use the previous critique to add important information to your answer.
        - You MUST include numerical citations in your revised answer to ensure it can be verified.
        - Add a "References" section to the bottom of your answer (which does not count towards the word limit). In form of:
            - [1] https://example.com
            - [2] https://example.com
    - You should use the previous critique to remove superfluous information from your answer and make SURE it is not more than 250 words.
"""

# reuse the llm as revisor but in revisor mmode just allow the "ReviseAnser" tool
# > as we reuse the actor_prompt_template, we have to change first_instruction to the revise_instructions
revisor = actor_prompt_template.partial(
    first_instruction=revise_instructions
) | llm.bind_tools(tools=[ReviseAnswer], tool_choice="ReviseAnswer")

# NOTE: in this revision we don't use the revisor yet
if __name__ == "__main__":
    human_message = HumanMessage(
        content="Write about AI-Powered SOC / autonomous soc  problem domain,"
        " list startups that do that and raised capital."
    )
    # chain is just as first_responder with the difference, 
    # that we put the output to the parser_pydantic to filter out the fields defined by "AnswerQuestion"
    # > otherwise we would get AnswerQuestion fields (due to forcing the tool_choice) but also additional metadate (I guess)
    chain = (
        first_responder_prompt_template
        | llm.bind_tools(tools=[AnswerQuestion], tool_choice="AnswerQuestion")
        | parser_pydantic
    )

    res = chain.invoke(input={"messages": [human_message]})
    print(res)
