[tool.poetry]
name = "reflexion-agent"
version = "0.1.0"
description = ""
authors = ["Eden Marco <emarco177@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
python-dotenv = "*"
black = "*"
isort = "*"
langchain = "*"
langchain-openai = "*"
langgraph = "*"
grandalf = "*"
ipykernel = "^7.2.0"
langchain-tavily = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
